# Generated by Django 3.0.7 on 2020-06-15 15:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200615_1133'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
