# Generated by Django 3.0.7 on 2020-06-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200615_1224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
    ]
