# Generated by Django 3.0.7 on 2020-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200615_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
